### ISSUE TITLE
[Question]changing hierarchy of list of list?

### ISSUE THREAD

**Issue by happyshows** [renkun-ken/rlist#106]
Hi,

I have a list of list like below:
A-GA-a
A-GA-b
A-GB-a
A-GB-b
B-GA-a
B-GA-b
B-GB-a
B-GB-b
and I'm wondering how to change it to:
GA-A-a
GA-A-b
GB-A-a
GB-A-b
GA-B-a
GA-B-b
GB-B-a
GB-B-b

Thanks...

**Comment by renkun-ken** [comment]
You may try `list.select`. For example, 

```
> lst <- list(list(x=1,y=2,z=3), list(x=3,y=2,z=3))
> str(list.select(lst, y, x, z))
List of 2
 $ :List of 3
  ..$ y: num 2
  ..$ x: num 1
  ..$ z: num 3
 $ :List of 3
  ..$ y: num 2
  ..$ x: num 3
  ..$ z: num 3
```

**Comment by happyshows** [comment]
@renkun-ken I think you might have misunderstand my ask, I was looking for some functions like the zip_n() in purrr package 

http://blog.rstudio.org/2015/09/29/purrr-0-1-0/

**Comment by renkun-ken** [comment]
I don't quite catch your demand. Would you please show a sample `list` object and the desired output?

**Comment by happyshows** [comment]
convert from
#> List of 2
#>  $ :List of 2
#>   ..$ a: num 1
#>   ..$ b: num 2
#>  $ :List of 2
#>   ..$ a: num 2
#>   ..$ b: num 1

to
#> List of 2
#>  $ a:List of 2
#>   ..$ : num 1
#>   ..$ : num 2
#>  $ b:List of 2
#>   ..$ : num 2
#>   ..$ : num 1

**Comment by renkun-ken** [comment]
Is this what you are trying to do?

```r
> library(rlist)
> x <- list(list(a=1,b=2), list(a=2,b=1))
> x
[[1]]
[[1]]$a
[1] 1

[[1]]$b
[1] 2


[[2]]
[[2]]$a
[1] 2

[[2]]$b
[1] 1


> list.unzip(x)
$a
[1] 1 2

$b
[1] 2 1
```

**Comment by happyshows** [comment]
yes, thanks..
