### ISSUE TITLE
Include an example in list.clean that evaluates using a character

### ISSUE THREAD

**Issue by Ironholds** [renkun-ken/rlist#108]
list.clean's documentation currently says it can evaluate over "a character". I'm not clear on what this means - it would be good if the documentation had an example.

**Comment by renkun-ken** [comment]
The argument `fun` of `list.clean` can be a `character` means that it can be, for example, either `"is.null"` or `is.null`, both work.

**Comment by Ironholds** [comment]
Gotcha. Why not 'a function, in quotes or not?'

**Comment by renkun-ken** [comment]
It works more like `*apply` functions which accept both `function` or `character` using `match.fun`.
