### ISSUE TITLE
list.names() does not work with .data=NULL and any expr

### ISSUE THREAD

**Issue by kablag** [renkun-ken/rlist#116]
`list.names(NULL, id)`
raises error:
`Error in list.names(NULL, a) : attempt to set an attribute on NULL`

I think it's better to return NULL in this case because other rlist functions work with NULL.

`list.names(NULL)`
returns empty list - list()

**Comment by renkun-ken** [comment]
Thanks for reporting this.

`list.names(.data, expr)` should return `names(.data)` when `expr` is missing and return a new list with names from mapping `.data` by `expr` when `expr` is supplied.

For `list.names(NULL)`, it should return `NULL` as it already does. But for `list.names(NULL, expr)`, setting names to `NULL` is not allowed so it should return `NULL` anyway.
