### ISSUE TITLE
How to search this kind of data?

### ISSUE THREAD

**Issue by hlblade** [renkun-ken/rlist#124]
```r
patients<-list(
  list(
    name="Jack",
    age=30,
    ucg=list(
      report=list(
        date="2019-10-01 15:36",
        EF=0.45,
        LV=60
      ),
      report=list(
        date="2019-10-11 16:40",
        EF=0.49,
        LV=58
      )
    )
  ),
  list(
    name="Jim",
    age=36,
    ucg=list(
      report=list(
        date="2019-09-01 09:36",
        EF=0.65,
        LV=60
      ),
      report=list(
        date="2019-09-11 16:50",
        EF=0.55,
        LV=58
      )
    )
  )
)
```
The structure looks like this:
List of 2
 $ :List of 3
  ..$ name: chr "Jack"
  ..$ age : num 30
  ..$ ucg :List of 2
  .. ..$ report:List of 3
  .. .. ..$ date: chr "2019-10-01 15:36"
  .. .. ..$ EF  : num 0.45
  .. .. ..$ LV  : num 60
  .. ..$ report:List of 3
  .. .. ..$ date: chr "2019-10-11 16:40"
  .. .. ..$ EF  : num 0.49
  .. .. ..$ LV  : num 58
 $ :List of 3
  ..$ name: chr "Jim"
  ..$ age : num 36
  ..$ ucg :List of 2
  .. ..$ report:List of 3
  .. .. ..$ date: chr "2019-09-01 09:36"
  .. .. ..$ EF  : num 0.65
  .. .. ..$ LV  : num 60
  .. ..$ report:List of 3
  .. .. ..$ date: chr "2019-09-11 16:50"
  .. .. ..$ EF  : num 0.55
  .. .. ..$ LV  : num 58
How to filter  patient who did ucg test at 2019-09-11 16:50?
list.filter(patients,ucg$report$date=="2019-09-11 16:50") doest work
Thanks in advanced!

**Comment by renkun-ken** [comment]
You may try

```r
res <- list.filter(patients, list.any(ucg, date == "2019-09-11 16:50"))
str(res)
```

```
List of 1
 $ :List of 3
  ..$ name: chr "Jim"
  ..$ age : num 36
  ..$ ucg :List of 2
  .. ..$ report:List of 3
  .. .. ..$ date: chr "2019-09-01 09:36"
  .. .. ..$ EF  : num 0.65
  .. .. ..$ LV  : num 60
  .. ..$ report:List of 3
  .. .. ..$ date: chr "2019-09-11 16:50"
  .. .. ..$ EF  : num 0.55
  .. .. ..$ LV  : num 58
```

**Comment by hlblade** [comment]
Thanks very much for your wonderful package and  swift reply!
