### ISSUE TITLE
rlist on CRAN will be archived at 2021-09-16

### ISSUE THREAD

**Issue by selesnow** [renkun-ken/rlist#130]
Hello!

I use `rlist` inside my own `rgoogleads` package, and today I received a letter from CRAN support that the `rlist` will be archived on September 16, if you do not make the necessary changes.

Do you plan to further support the package, and make the necessary changes to the CRAN?

**Comment by renkun-ken** [comment]
Looks like it is an upstream issue of stringdist error. Let me refine the test cases so that the tests on CRAN could pass.

**Comment by selesnow** [comment]
Thanks.

Part of the letter from the CRANE team:

> We have asked for an update fixing the check problems shown at
>   <https://cran.r-project.org/web/checks/check_results_rlist.html>
> with no update from the maintainer thus far.
> 
> Thus, package rlist is now scheduled for archival on 2021-09-16, and
> archiving this will necessitate also archiving its strong reverse
> dependencies.

**Comment by selesnow** [comment]
Trouble in tests:

```
Running the tests in ‘tests/testthat.R’ failed.
Complete output:
  > library(testthat)
  > test_check("rlist") 
  Loading required package: rlist
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Error (test-search.R:30:3): list.search ─────────────────────────────────────
  Error: there is no package called 'stringdist'
  Backtrace:
      █
   1. ├─testthat::expect_equal(...) test-search.R:30:2
   2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
   3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
   4. └─rlist::list.search(...)
   5.   └─rlist:::tryWithCondition(...)
   6.     └─base::tryCatch(...)
   7.       └─base:::tryCatchList(expr, classes, parentenv, handlers)
   8.         └─base:::tryCatchOne(expr, names, parentenv, handlers[[1L]])
   9.           └─value[[3L]](cond)
  
  [ FAIL 1 | WARN 0 | SKIP 0 | PASS 282 ]
  Error: Test failures
  Execution halted
```

**Comment by renkun-ken** [comment]
Submitted.

**Comment by selesnow** [comment]
Thanks a lot!

**Comment by renkun-ken** [comment]
The CRAN release has been updated.

**Comment by selesnow** [comment]
Thanks!
